;-----------------------------------------------------------------------
include     windows.inc
include     macros.asm
include     xmacros.mac
include     slib.mac

;-----------------------------------------------------------------------
includes    resources.inc, kernel32, user32, advapi32, masm32, slib, xlib, blowfish, sha1

;-----------------------------------------------------------------------
