;-----------------------------------------------------------------------
IDI_ICON equ 100

IDD_HIDE equ 200
IDD_DLG  equ 201
IDD_HELP equ 203

IDS_NAME         equ 300
IDS_ACTIVATION   equ 301
IDS_REGISTRATION equ 302

IDE_NAME         equ 400
IDE_ACTIVATION   equ 401
IDE_REGISTRATION equ 402
IDE_HELP         equ 403

IDB_HELP   equ 500
IDB_VERIFY equ 501
IDB_CLOSE  equ 502
IDB_CLOSEHELP equ 503

IDR_HELP   equ 600

;-----------------------------------------------------------------------
